# Pre-commit hooks for Erguvan AI Content Generator
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.9
        args: ["--line-length=88", "--target-version=py39"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: ["--ignore-missing-imports", "--no-strict-optional"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "88"]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        files: ^pyproject\.toml$
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd /Users/eyuphankoc/Projects/erguvan_content_generator && source venv/bin/activate && python -m pytest tests/ -xvs'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

exclude: |
  (?x)^(
    .*\.egg-info/.*|
    build/.*|
    dist/.*|
    \.git/.*|
    \.mypy_cache/.*|
    \.pytest_cache/.*|
    \.venv/.*|
    venv/.*|
    __pycache__/.*
  )$