# ============================================================
#  Erguvan Brand Voice & Content Guide
#  v2025-07-16  |  Maintainer: Brand & Comms Team
#  License: CC BY-NC-SA 4.0
# ============================================================

metadata:
  company: "Erguvan"
  narrative: >
    Erguvan is Türkiye’s first digital carbon-credit marketplace and ESG
    data provider, integrating voluntary offset trading (ECM) with Azalt,
    an AI-driven carbon & ESG management SaaS used by corporates and banks.
  tagline: "Powering Climate Action with Finance & Data"
  pillars: ["Credibility", "Clarity", "Actionability", "Empowerment"]

voice:
  personality:
    primary: "authoritative-yet-approachable"
    traits:
      - transparent
      - solutions-oriented
      - evidence-backed
      - collaborative
  tonal_slider:                # choose one per deliverable
    - expert_report            # white-papers, policy briefs
    - pragmatic_advisory       # implementation guides, playbooks
    - inspirational            # keynotes, thought-leadership
  never_use:
    - sensationalism
    - un-sourced claims
    - unexplained jargon
    - empty buzzwords
    - guilt-tripping rhetoric

readability_targets:
  flesch_kincaid_grade_max: 12
  sentence_length_avg: 15-22  # words
  passive_voice_max_pct: 10

multilingual:
  default_language: "EN"
  supported_languages: ["EN", "TR"]
  translation_rules:
    - maintain metric units
    - localise regulatory names (TR ETS → “Türkiye Emisyon Ticareti Sistemi”)
    - keep product names in English (ECM, Azalt)

audience_profiles:
  - name: "C-Suite & Boards"
    info_needs: ["risk-mitigation", "ROI", "regulatory exposure"]
    deliverable_len: "≤ 800 words (exec summary); ≤ 10 slides"
  - name: "Sustainability Leads / ESG Managers"
    info_needs: ["methodology depth", "data fields", "implementation steps"]
    deliverable_len: "1 500-3 000 words; detailed annexes"
  - name: "Bank & Fintech Partners"
    info_needs: ["product integration", "KPIs", "case studies"]
    deliverable_len: "≤ 1 200 words; diagram-rich"

structure_defaults:
  document:
    preamble: ["Key takeaway", "Why it matters now"]
    body_sections: ["Context", "Implications", "Recommendations"]
    close: ["Next steps", "Further reading", "Contact"]
  blog_post:
    preamble: ["TL;DR bullet list"]
    length: 750-1 100 words
    CTA: "Book a demo"

style_conventions:
  headings: "verb-led, ≤ 8 words"
  bullets: "parallel, active voice"
  emphasis:
    bold: "key terms"
    italics: "definitions, legislation"
  numerals: "always use digits for 10+; spell out one-nine"
  citations:
    style: "Chicago author-date (hyper-linked)"
    required_for: ["stats", "quotes", "legislation"]

quality_gate:
  plagiarism_max_pct: 10
  brand_tone_match_min: 90     # vs. this guide using ML classifier
  fact_currency_months: 12
  human_review_required: true  # before external release

domain_knowledge:
  focus_topics:
    - climate_policy (EU CBAM, TR ETS)
    - carbon_accounting (GHG Protocol, ISO 14064)
    - voluntary_carbon_markets (Verra, Gold Standard)
    - ESG_reporting (CSRD, TCFD, SBTi)
    - sustainable_finance (green loans, transition bonds)
  regulatory_hotlist:
    - EU CBAM definitive phase 2026
    - Turkey Climate Law 2025
    - CSRD phased entry 2025-2028

do_dont_examples:
  - do: "Provide quantified impact: *“The TR ETS will cover ~70 % of national emissions by 2025.”*"
    dont: "Use vague clichés: *“Turkey is going big on green.”*"
  - do: "Define acronyms on first use."
    dont: "Assume reader knows CBAM, ETS, MRV."

asset_output:
  formats_allowed: [".md", ".docx", ".pptx"]
  naming_pattern: "<YYYYMMDD>_<topic>_<audience>_Erguvan"
  docx_template_path: "/templates/ErguvanReport.docx"
